import crypto from 'node:crypto';
import {
  and,
  asc,
  desc,
  eq,
  gte,
  ilike,
  inArray,
  or,
  sql
} from 'drizzle-orm';
import { db } from '@/lib/db/drizzle';
import {
  businessSettings,
  businesses,
  connectedAccounts,
  locations,
  notifications,
  replyDrafts,
  reviewAnalysis,
  reviews,
  teamMembers,
  users,
  type Business,
  type BusinessSettings,
  type ConnectedAccount,
  type Location,
  type ReplyDraft,
  type Review,
  type ReviewAnalysis
} from '@/lib/db/schema';
import {
  analyzeReviewWithAI,
  generateReplyDraftWithAI
} from '@/lib/services/ai';
import {
  resolveWorkflowStatusesForFilters,
  type ReviewStatusGroup
} from '@/lib/services/reviews/inbox-filters';
import { sortReviewsForInbox, type ReviewSortMode } from '@/lib/services/reviews/inbox';
import {
  assertDraftGenerationAllowed,
  shouldAutoGenerateDraft
} from '@/lib/services/reviews/draft-generation-policy';
import { AbuseProtectionError } from '@/lib/services/reviews/abuse-protection';
import {
  resolveFocusQueueAction,
  shouldEscalateAfterAnalysis,
  sortFocusQueueCandidates,
  type FocusQueueNextAction
} from '@/lib/services/reviews/focus-queue';
import { queueJob } from '@/lib/services/job-queue';
import { fetchReviewsForLocation } from '@/lib/services/integrations/google';

export type ReviewFilters = {
  locationId?: number;
  status?: string;
  statusGroup?: ReviewStatusGroup;
  rating?: number;
  urgency?: string;
  search?: string;
  sort?: ReviewSortMode;
};

type ReviewWithContext = Review & {
  location: Location;
  latestAnalysis: ReviewAnalysis | null;
  latestDraft: ReplyDraft | null;
};

type OwnerContact = {
  id: number;
  email: string;
};

const FOCUS_QUEUE_ACTIONABLE_STATUSES = [
  'needs_attention',
  'rejected',
  'analyzed',
  'draft_ready',
  'approved'
] as const;

const RECENT_HANDLED_WORKFLOW_STATUSES = [
  'approved',
  'posted_manual',
  'closed_no_reply'
] as const;

export type FocusQueueReview = {
  review: ReviewWithContext;
  nextAction: FocusQueueNextAction;
  reason: string;
};

type FocusQueueOptions = {
  excludeReviewIds?: number[];
};

export class ReviewMutationAccessError extends Error {
  readonly code = 'forbidden_scope';
  readonly status = 403;

  constructor(message = 'Access to this review or draft is forbidden for the current workspace.') {
    super(message);
    this.name = 'ReviewMutationAccessError';
  }
}

export function isReviewMutationAccessError(
  error: unknown
): error is ReviewMutationAccessError {
  return error instanceof ReviewMutationAccessError;
}

const DRAFT_REVIEW_COOLDOWN_MS = 20_000;
const DRAFT_BUSINESS_WINDOW_MS = 5 * 60_000;
const DRAFT_BUSINESS_MAX_ATTEMPTS = 12;
const DRAFT_REVIEW_DAILY_WINDOW_MS = 24 * 60 * 60_000;
const DRAFT_REVIEW_DAILY_MAX_ATTEMPTS = 8;
const DRAFT_USER_TRIGGERED_GENERATION_REASONS = ['manual', 'regenerate'] as const;
const ANALYSIS_REVIEW_COOLDOWN_MS = 20_000;

export async function listBusinessLocations(businessId: number) {
  return db
    .select({
      id: locations.id,
      name: locations.name
    })
    .from(locations)
    .where(eq(locations.businessId, businessId))
    .orderBy(asc(locations.name));
}

function hashPayload(payload: unknown) {
  return crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex');
}

async function getBusinessContextForReview(reviewId: number) {
  const reviewRecord = await db.query.reviews.findFirst({
    where: eq(reviews.id, reviewId)
  });

  if (!reviewRecord) {
    throw new Error('Review not found');
  }

  const location = await db.query.locations.findFirst({
    where: eq(locations.id, reviewRecord.locationId)
  });

  if (!location) {
    throw new Error('Location not found');
  }

  const business = await db.query.businesses.findFirst({
    where: eq(businesses.id, location.businessId)
  });

  if (!business) {
    throw new Error('Business not found');
  }

  const settings = await db.query.businessSettings.findFirst({
    where: eq(businessSettings.businessId, business.id)
  });

  if (!settings) {
    throw new Error('Business settings not found');
  }

  return { review: reviewRecord, location, business, settings };
}

function computeRetryAfterSeconds(cutoffTimestampMs: number) {
  const remainingMs = cutoffTimestampMs - Date.now();
  if (remainingMs <= 0) {
    return 1;
  }
  return Math.max(1, Math.ceil(remainingMs / 1000));
}

async function enforceDraftGenerationAbuseProtection({
  reviewId,
  businessId
}: {
  reviewId: number;
  businessId: number;
}) {
  const [latestManualDraft] = await db
    .select({ createdAt: replyDrafts.createdAt })
    .from(replyDrafts)
    .where(
      and(
        eq(replyDrafts.reviewId, reviewId),
        inArray(
          replyDrafts.generationReason,
          DRAFT_USER_TRIGGERED_GENERATION_REASONS
        )
      )
    )
    .orderBy(desc(replyDrafts.createdAt))
    .limit(1);

  if (latestManualDraft?.createdAt) {
    const cooldownEnd = latestManualDraft.createdAt.getTime() + DRAFT_REVIEW_COOLDOWN_MS;
    if (Date.now() < cooldownEnd) {
      throw new AbuseProtectionError(
        'draft_generation_rate_limited',
        'Draft generation is being requested too quickly for this review.',
        computeRetryAfterSeconds(cooldownEnd)
      );
    }
  }

  const windowStart = new Date(Date.now() - DRAFT_BUSINESS_WINDOW_MS);
  const [windowUsage] = await db
    .select({
      count: sql<number>`count(*)`
    })
    .from(replyDrafts)
    .innerJoin(reviews, eq(reviews.id, replyDrafts.reviewId))
    .innerJoin(locations, eq(locations.id, reviews.locationId))
    .where(
      and(
        eq(locations.businessId, businessId),
        inArray(
          replyDrafts.generationReason,
          DRAFT_USER_TRIGGERED_GENERATION_REASONS
        ),
        gte(replyDrafts.createdAt, windowStart)
      )
    );

  const attemptsInWindow = Number(windowUsage?.count ?? 0);
  if (attemptsInWindow >= DRAFT_BUSINESS_MAX_ATTEMPTS) {
    throw new AbuseProtectionError(
      'draft_generation_rate_limited',
      'Draft generation rate limit exceeded. Please wait before trying again.',
      Math.ceil(DRAFT_BUSINESS_WINDOW_MS / 1000)
    );
  }

  const dailyWindowStart = new Date(Date.now() - DRAFT_REVIEW_DAILY_WINDOW_MS);
  const [dailyUsage] = await db
    .select({
      count: sql<number>`count(*)`,
      oldestAttemptAt: sql<Date | string | null>`min(${replyDrafts.createdAt})`
    })
    .from(replyDrafts)
    .where(
      and(
        eq(replyDrafts.reviewId, reviewId),
        inArray(
          replyDrafts.generationReason,
          DRAFT_USER_TRIGGERED_GENERATION_REASONS
        ),
        gte(replyDrafts.createdAt, dailyWindowStart)
      )
    );

  const dailyAttempts = Number(dailyUsage?.count ?? 0);
  if (dailyAttempts >= DRAFT_REVIEW_DAILY_MAX_ATTEMPTS) {
    const oldestAttempt = dailyUsage?.oldestAttemptAt
      ? new Date(dailyUsage.oldestAttemptAt).getTime()
      : Date.now();
    const nextAttemptAt = oldestAttempt + DRAFT_REVIEW_DAILY_WINDOW_MS;

    throw new AbuseProtectionError(
      'draft_generation_rate_limited',
      'Daily draft generation limit reached for this review. Please try again later.',
      computeRetryAfterSeconds(nextAttemptAt)
    );
  }
}

async function enforceAnalysisAbuseProtection(reviewId: number) {
  const [latestAnalysis] = await db
    .select({ createdAt: reviewAnalysis.createdAt })
    .from(reviewAnalysis)
    .where(eq(reviewAnalysis.reviewId, reviewId))
    .orderBy(desc(reviewAnalysis.createdAt))
    .limit(1);

  if (!latestAnalysis?.createdAt) {
    return;
  }

  const cooldownEnd = latestAnalysis.createdAt.getTime() + ANALYSIS_REVIEW_COOLDOWN_MS;
  if (Date.now() >= cooldownEnd) {
    return;
  }

  throw new AbuseProtectionError(
    'analysis_rate_limited',
    'Analysis is being requested too quickly for this review.',
    computeRetryAfterSeconds(cooldownEnd)
  );
}

async function getBusinessOwnerContact(teamId: number): Promise<OwnerContact | null> {
  const [owner] = await db
    .select({
      id: users.id,
      email: users.email
    })
    .from(teamMembers)
    .innerJoin(users, eq(users.id, teamMembers.userId))
    .where(and(eq(teamMembers.teamId, teamId), eq(teamMembers.role, 'owner')))
    .orderBy(asc(teamMembers.joinedAt))
    .limit(1);

  return owner ?? null;
}

async function getLatestAnalyses(reviewIds: number[]) {
  if (reviewIds.length === 0) {
    return new Map<number, ReviewAnalysis>();
  }

  const rows = await db
    .select()
    .from(reviewAnalysis)
    .where(and(inArray(reviewAnalysis.reviewId, reviewIds), eq(reviewAnalysis.isActive, true)));

  return new Map(rows.map((row) => [row.reviewId, row]));
}

async function getLatestDrafts(reviewIds: number[]) {
  if (reviewIds.length === 0) {
    return new Map<number, ReplyDraft>();
  }

  const rows = await db
    .select()
    .from(replyDrafts)
    .where(and(inArray(replyDrafts.reviewId, reviewIds), eq(replyDrafts.isActive, true)));

  return new Map(rows.map((row) => [row.reviewId, row]));
}

async function buildReviewRecords(baseReviews: Review[]) {
  const locationIds = [...new Set(baseReviews.map((review) => review.locationId))];
  const reviewIds = baseReviews.map((review) => review.id);

  const [locationRows, analysisMap, draftMap] = await Promise.all([
    db.select().from(locations).where(inArray(locations.id, locationIds)),
    getLatestAnalyses(reviewIds),
    getLatestDrafts(reviewIds)
  ]);

  const locationMap = new Map(locationRows.map((location) => [location.id, location]));

  return baseReviews.map((review) => ({
    ...review,
    location: locationMap.get(review.locationId)!,
    latestAnalysis: analysisMap.get(review.id) ?? null,
    latestDraft: draftMap.get(review.id) ?? null
  }));
}

export async function getDashboardSummary(businessId: number) {
  const businessLocations = await db
    .select({ id: locations.id })
    .from(locations)
    .where(eq(locations.businessId, businessId));

  const locationIds = businessLocations.map((location) => location.id);
  if (locationIds.length === 0) {
    return {
      newReviews: 0,
      urgentReviews: 0,
      readyToPost: 0,
      postedThisWeek: 0,
      totalLocations: 0
    };
  }

  const [[counts], [urgentCounts]] = await Promise.all([
    db
      .select({
        newReviews: sql<number>`count(*) filter (where ${reviews.workflowStatus} = 'new')`,
        readyToPost: sql<number>`count(*) filter (where ${reviews.workflowStatus} in ('draft_ready', 'approved'))`,
        postedThisWeek: sql<number>`count(*) filter (where ${reviews.workflowStatus} = 'posted_manual' and ${reviews.updatedAt} >= now() - interval '7 days')`
      })
      .from(reviews)
      .where(inArray(reviews.locationId, locationIds)),
    db
      .select({
        urgentReviews: sql<number>`count(distinct ${reviews.id})`
      })
      .from(reviews)
      .innerJoin(reviewAnalysis, eq(reviewAnalysis.reviewId, reviews.id))
      .where(
        and(
          inArray(reviews.locationId, locationIds),
          eq(reviewAnalysis.isActive, true),
          inArray(reviewAnalysis.urgency, ['high', 'critical'])
        )
      )
  ]);

  return {
    newReviews: Number(counts?.newReviews ?? 0),
    urgentReviews: Number(urgentCounts?.urgentReviews ?? 0),
    readyToPost: Number(counts?.readyToPost ?? 0),
    postedThisWeek: Number(counts?.postedThisWeek ?? 0),
    totalLocations: locationIds.length
  };
}

export async function listBusinessReviews(
  businessId: number,
  filters: ReviewFilters = {}
) {
  const businessLocations = await db
    .select()
    .from(locations)
    .where(eq(locations.businessId, businessId));

  const locationIds = businessLocations.map((location) => location.id);
  if (locationIds.length === 0) {
    return [] as ReviewWithContext[];
  }

  const predicates = [inArray(reviews.locationId, locationIds)];

  if (filters.locationId) {
    predicates.push(eq(reviews.locationId, filters.locationId));
  }
  const workflowStatuses = resolveWorkflowStatusesForFilters({
    statusGroup: filters.statusGroup,
    status: filters.status
  });
  if (workflowStatuses?.length) {
    predicates.push(inArray(reviews.workflowStatus, workflowStatuses));
  }
  if (filters.rating) {
    predicates.push(eq(reviews.starRating, filters.rating));
  }
  if (filters.search) {
    predicates.push(
      or(
        ilike(reviews.reviewText, `%${filters.search}%`),
        ilike(reviews.reviewerName, `%${filters.search}%`)
      )!
    );
  }

  const candidateLimit = filters.sort === 'newest' ? 100 : 500;

  let rows = await db
    .select()
    .from(reviews)
    .where(and(...predicates))
    .orderBy(desc(reviews.reviewCreatedAt))
    .limit(candidateLimit);

  rows = await maybeFilterByUrgency(rows, filters.urgency);

  const records = await buildReviewRecords(rows);
  const sorted = sortReviewsForInbox(records, filters.sort ?? 'urgency_then_newest');
  return sorted.slice(0, 100);
}

export async function listRecentHandledReviews(businessId: number, limit = 5) {
  const businessLocations = await db
    .select({ id: locations.id })
    .from(locations)
    .where(eq(locations.businessId, businessId));

  const locationIds = businessLocations.map((location) => location.id);
  if (locationIds.length === 0) {
    return [] as ReviewWithContext[];
  }

  const rows = await db
    .select()
    .from(reviews)
    .where(
      and(
        inArray(reviews.locationId, locationIds),
        inArray(reviews.workflowStatus, [...RECENT_HANDLED_WORKFLOW_STATUSES])
      )
    )
    .orderBy(desc(reviews.updatedAt))
    .limit(limit);

  return buildReviewRecords(rows);
}

async function maybeFilterByUrgency(rows: Review[], urgency?: string) {
  if (!urgency || rows.length === 0) {
    return rows;
  }

  const analyses = await getLatestAnalyses(rows.map((row) => row.id));
  if (urgency === 'urgent') {
    return rows.filter((row) => {
      const analysisUrgency = analyses.get(row.id)?.urgency;
      return analysisUrgency === 'high' || analysisUrgency === 'critical';
    });
  }

  return rows.filter((row) => analyses.get(row.id)?.urgency === urgency);
}

export async function getReviewDetail(businessId: number, reviewId: number) {
  const review = await db.query.reviews.findFirst({
    where: eq(reviews.id, reviewId)
  });

  if (!review) {
    return null;
  }

  const location = await db.query.locations.findFirst({
    where: and(eq(locations.id, review.locationId), eq(locations.businessId, businessId))
  });

  if (!location) {
    return null;
  }

  const [business, settings, analyses, drafts] = await Promise.all([
    db.query.businesses.findFirst({
      where: eq(businesses.id, businessId)
    }),
    db.query.businessSettings.findFirst({
      where: eq(businessSettings.businessId, businessId)
    }),
    db
      .select()
      .from(reviewAnalysis)
      .where(eq(reviewAnalysis.reviewId, reviewId))
      .orderBy(desc(reviewAnalysis.analysisVersion)),
    db
      .select()
      .from(replyDrafts)
      .where(eq(replyDrafts.reviewId, reviewId))
      .orderBy(desc(replyDrafts.version))
  ]);

  return {
    review,
    location,
    business: business!,
    settings: settings!,
    analyses,
    drafts,
    latestAnalysis: analyses[0] ?? null,
    latestDraft: drafts[0] ?? null
  };
}

async function getBusinessScopedReview(businessId: number, reviewId: number) {
  const [row] = await db
    .select({
      review: reviews
    })
    .from(reviews)
    .innerJoin(locations, eq(locations.id, reviews.locationId))
    .where(and(eq(reviews.id, reviewId), eq(locations.businessId, businessId)))
    .limit(1);

  return row?.review ?? null;
}

async function getBusinessScopedDraft(businessId: number, draftId: number) {
  const [row] = await db
    .select({
      draft: replyDrafts
    })
    .from(replyDrafts)
    .innerJoin(reviews, eq(reviews.id, replyDrafts.reviewId))
    .innerJoin(locations, eq(locations.id, reviews.locationId))
    .where(and(eq(replyDrafts.id, draftId), eq(locations.businessId, businessId)))
    .limit(1);

  return row?.draft ?? null;
}

async function assertReviewMutationAccess(reviewId: number, businessId?: number) {
  if (!businessId) {
    return;
  }

  const scopedReview = await getBusinessScopedReview(businessId, reviewId);
  if (scopedReview) {
    return;
  }

  const [existingReview] = await db
    .select({ id: reviews.id })
    .from(reviews)
    .where(eq(reviews.id, reviewId))
    .limit(1);

  if (existingReview) {
    throw new ReviewMutationAccessError();
  }

  throw new Error('Review not found');
}

async function assertDraftMutationAccess(draftId: number, businessId?: number) {
  if (!businessId) {
    return;
  }

  const scopedDraft = await getBusinessScopedDraft(businessId, draftId);
  if (scopedDraft) {
    return;
  }

  const [existingDraft] = await db
    .select({ id: replyDrafts.id })
    .from(replyDrafts)
    .where(eq(replyDrafts.id, draftId))
    .limit(1);

  if (existingDraft) {
    throw new ReviewMutationAccessError();
  }

  throw new Error('Draft not found');
}

export async function getFocusQueueReview(
  businessId: number,
  options: FocusQueueOptions = {}
): Promise<FocusQueueReview | null> {
  const [businessLocations, business] = await Promise.all([
    db.select({ id: locations.id }).from(locations).where(eq(locations.businessId, businessId)),
    db.query.businesses.findFirst({
      where: eq(businesses.id, businessId)
    })
  ]);

  const locationIds = businessLocations.map((location) => location.id);
  if (locationIds.length === 0 || !business) {
    return null;
  }

  const candidates = await db
    .select()
    .from(reviews)
    .where(
      and(
        inArray(reviews.locationId, locationIds),
        inArray(reviews.workflowStatus, [...FOCUS_QUEUE_ACTIONABLE_STATUSES])
      )
    )
    .limit(400);

  if (candidates.length === 0) {
    return null;
  }

  const excludedIds = new Set(options.excludeReviewIds ?? []);
  const eligibleCandidates = excludedIds.size
    ? candidates.filter((candidate) => !excludedIds.has(candidate.id))
    : candidates;

  if (eligibleCandidates.length === 0) {
    return null;
  }

  const records = await buildReviewRecords(eligibleCandidates);
  const owner = await getBusinessOwnerContact(business.teamId);
  const sorted = sortFocusQueueCandidates(records, owner?.id ?? null);
  const topCandidate = sorted[0];

  if (!topCandidate) {
    return null;
  }

  const topRecord = records.find((record) => record.id === topCandidate.id);
  if (!topRecord) {
    return null;
  }

  const resolution = resolveFocusQueueAction(topCandidate);
  return {
    review: topRecord,
    nextAction: resolution.nextAction,
    reason: resolution.reason
  };
}

export async function syncConnectedAccountReviews(connectedAccountId: number) {
  const account = await db.query.connectedAccounts.findFirst({
    where: eq(connectedAccounts.id, connectedAccountId)
  });

  if (!account) {
    throw new Error('Connected account not found');
  }

  const accountLocations = await db
    .select()
    .from(locations)
    .where(
      and(
        eq(locations.connectedAccountId, account.id),
        eq(locations.status, 'active')
      )
    );

  let importedCount = 0;

  for (const location of accountLocations) {
    const fetchedReviews = await fetchReviewsForLocation(account, location);

    for (const review of fetchedReviews) {
      const payloadHash = hashPayload(review.rawPayload);
      const [existing] = await db
        .select()
        .from(reviews)
        .where(
          and(
            eq(reviews.locationId, location.id),
            eq(reviews.externalReviewId, review.externalReviewId),
            eq(reviews.provider, 'google_business_profile')
          )
        )
        .limit(1);

      if (existing && existing.payloadHash === payloadHash) {
        continue;
      }

      if (existing) {
        const [updated] = await db
          .update(reviews)
          .set({
            reviewerName: review.reviewerName,
            reviewerPhotoUrl: review.reviewerPhotoUrl,
            starRating: review.starRating,
            reviewText: review.reviewText,
            reviewCreatedAt: review.reviewCreatedAt,
            reviewUpdatedAt: review.reviewUpdatedAt,
            ownerReplyText: review.ownerReplyText,
            ownerReplyUpdatedAt: review.ownerReplyUpdatedAt,
            hasOwnerReply: Boolean(review.ownerReplyText),
            sourceUrl: review.sourceUrl,
            payloadHash,
            rawPayload: review.rawPayload,
            workflowStatus: 'new',
            priority: existing.priority,
            needsAttention: false,
            updatedAt: new Date()
          })
          .where(eq(reviews.id, existing.id))
          .returning();

        await queueJob({
          jobType: 'analyze_review',
          idempotencyKey: `analyze:${updated.id}:${payloadHash}`,
          payload: { reviewId: updated.id, payloadHash }
        });
      } else {
        const [created] = await db
          .insert(reviews)
          .values({
            locationId: location.id,
            provider: 'google_business_profile',
            externalReviewId: review.externalReviewId,
            reviewerName: review.reviewerName,
            reviewerPhotoUrl: review.reviewerPhotoUrl,
            starRating: review.starRating,
            reviewText: review.reviewText,
            reviewCreatedAt: review.reviewCreatedAt,
            reviewUpdatedAt: review.reviewUpdatedAt,
            ownerReplyText: review.ownerReplyText,
            ownerReplyUpdatedAt: review.ownerReplyUpdatedAt,
            hasOwnerReply: Boolean(review.ownerReplyText),
            sourceUrl: review.sourceUrl,
            payloadHash,
            rawPayload: review.rawPayload,
            workflowStatus: 'new',
            priority: review.starRating <= 2 ? 'high' : 'low',
            needsAttention: review.starRating <= 2
          })
          .returning();

        await queueJob({
          jobType: 'analyze_review',
          idempotencyKey: `analyze:${created.id}:${payloadHash}`,
          payload: { reviewId: created.id, payloadHash }
        });
      }

      importedCount += 1;
    }

    await db
      .update(locations)
      .set({
        lastSyncedAt: new Date(),
        syncError: null,
        updatedAt: new Date()
      })
      .where(eq(locations.id, location.id));
  }

  await db
    .update(connectedAccounts)
    .set({
      lastSyncAt: new Date(),
      status: 'active',
      lastError: null,
      updatedAt: new Date()
    })
    .where(eq(connectedAccounts.id, connectedAccountId));

  return {
    importedCount,
    locationCount: accountLocations.length
  };
}

export async function analyzeStoredReview(
  reviewId: number,
  options: { bypassAbuseProtection?: boolean; businessId?: number } = {}
) {
  await assertReviewMutationAccess(reviewId, options.businessId);

  if (!options.bypassAbuseProtection) {
    await enforceAnalysisAbuseProtection(reviewId);
  }

  const { review, business, settings } = await getBusinessContextForReview(reviewId);
  const analysis = await analyzeReviewWithAI(review, {
    vertical: business.vertical
  });
  const ownerContact = await getBusinessOwnerContact(business.teamId);

  const existingVersions = await db
    .select({
      version: reviewAnalysis.analysisVersion
    })
    .from(reviewAnalysis)
    .where(eq(reviewAnalysis.reviewId, reviewId))
    .orderBy(desc(reviewAnalysis.analysisVersion))
    .limit(1);

  await db
    .update(reviewAnalysis)
    .set({
      isActive: false
    })
    .where(eq(reviewAnalysis.reviewId, reviewId));

  const [createdAnalysis] = await db
    .insert(reviewAnalysis)
    .values({
      reviewId,
      sentiment: analysis.sentiment,
      urgency: analysis.urgency,
      riskLevel: analysis.riskLevel,
      issueTags: analysis.issueTags,
      summary: analysis.summary,
      actionRecommendation: analysis.actionRecommendation,
      confidence: analysis.confidence,
      requiresManualReview: analysis.requiresManualReview,
      analysisVersion: (existingVersions[0]?.version ?? 0) + 1,
      isActive: true,
      rawOutput: analysis.rawOutput,
      modelName: analysis.modelName
    })
    .returning();

  const shouldEscalate = shouldEscalateAfterAnalysis({
    starRating: review.starRating,
    requiresManualReview: analysis.requiresManualReview,
    riskLevel: analysis.riskLevel
  });

  const workflowStatus = shouldEscalate ? 'needs_attention' : 'analyzed';

  await db
    .update(reviews)
    .set({
      workflowStatus,
      priority: analysis.urgency,
      needsAttention: shouldEscalate,
      assignedUserId: shouldEscalate ? (ownerContact?.id ?? null) : null,
      escalatedAt: shouldEscalate ? new Date() : null,
      lastProcessedAt: new Date(),
      updatedAt: new Date()
    })
    .where(eq(reviews.id, reviewId));

  if (shouldEscalate && ownerContact?.email) {
    const [escalationNotification] = await db
      .insert(notifications)
      .values({
        businessId: business.id,
        reviewId,
        type: 'owner_escalation',
        channel: 'email',
        recipient: ownerContact.email,
        subject: `Review escalation for ${business.name}`,
        payload: {
          reviewId,
          analysisId: createdAnalysis.id,
          rating: review.starRating,
          riskLevel: analysis.riskLevel,
          urgency: analysis.urgency
        }
      })
      .returning();

    await queueJob({
      jobType: 'send_notification',
      idempotencyKey: `notification:owner_escalation:${reviewId}:${createdAnalysis.id}:${ownerContact.email}`,
      payload: { notificationId: escalationNotification.id }
    });
  }

  if (
    shouldAutoGenerateDraft({
      draftGenerationMode: settings.draftGenerationMode,
      starRating: review.starRating,
      riskLevel: analysis.riskLevel,
      requiresManualReview: analysis.requiresManualReview,
      confidence: analysis.confidence,
      actionRecommendation: analysis.actionRecommendation
    })
  ) {
    await queueJob({
      jobType: 'generate_draft',
      idempotencyKey: `draft:${reviewId}:${createdAnalysis.id}:initial`,
      payload: {
        reviewId,
        analysisId: createdAnalysis.id,
        generationReason: 'initial'
      }
    });
  }

  if (analysis.urgency === 'high' || analysis.urgency === 'critical') {
    const recipients =
      settings.notificationEmails.length > 0
        ? settings.notificationEmails
        : business.reviewContactEmail
        ? [business.reviewContactEmail]
        : [];

    for (const recipient of recipients) {
      const [notification] = await db
        .insert(notifications)
        .values({
          businessId: business.id,
          reviewId,
          type: 'urgent_review',
          channel: 'email',
          recipient,
          subject: `Urgent review for ${business.name}`,
          payload: {
            rating: review.starRating,
            reviewText: review.reviewText,
            urgency: analysis.urgency,
            locationId: review.locationId
          }
        })
        .returning();

      await queueJob({
        jobType: 'send_notification',
        idempotencyKey: `notification:${notification.id}`,
        payload: { notificationId: notification.id }
      });
    }
  }

  return createdAnalysis;
}

export async function generateDraftForReview(
  reviewId: number,
  generationReason = 'manual',
  options: { bypassAbuseProtection?: boolean; businessId?: number } = {}
) {
  await assertReviewMutationAccess(reviewId, options.businessId);

  const { review, business, settings } = await getBusinessContextForReview(reviewId);
  if (
    !options.bypassAbuseProtection &&
    (generationReason === 'manual' || generationReason === 'regenerate')
  ) {
    await enforceDraftGenerationAbuseProtection({
      reviewId,
      businessId: business.id
    });
  }

  const analysis = await db.query.reviewAnalysis.findFirst({
    where: and(eq(reviewAnalysis.reviewId, reviewId), eq(reviewAnalysis.isActive, true))
  });

  if (!analysis) {
    throw new Error('Review analysis not found');
  }
  assertDraftGenerationAllowed(analysis.actionRecommendation);

  const latestVersion = await db
    .select({
      version: replyDrafts.version
    })
    .from(replyDrafts)
    .where(eq(replyDrafts.reviewId, reviewId))
    .orderBy(desc(replyDrafts.version))
    .limit(1);

  await db
    .update(replyDrafts)
    .set({
      isActive: false,
      updatedAt: new Date()
    })
    .where(eq(replyDrafts.reviewId, reviewId));

  const draft = await generateReplyDraftWithAI({
    review,
    business,
    settings,
    analysis
  });

  const [createdDraft] = await db
    .insert(replyDrafts)
    .values({
      reviewId,
      analysisId: analysis.id,
      draftText: draft.draftText,
      tone: draft.tone,
      ctaType: draft.ctaType,
      safetyNotes: draft.safetyNotes,
      generationMetadata: draft.generationMetadata,
      generationReason,
      draftStatus: 'generated',
      version: (latestVersion[0]?.version ?? 0) + 1,
      isActive: true
    })
    .returning();

  await db
    .update(reviews)
    .set({
      workflowStatus: analysis.requiresManualReview ? 'needs_attention' : 'draft_ready',
      updatedAt: new Date()
    })
    .where(eq(reviews.id, reviewId));

  return createdDraft;
}

export type DraftMutationResult = {
  draft: ReplyDraft;
  wasNoop: boolean;
};

export type ReviewMutationResult = {
  review: Review;
  wasNoop: boolean;
};

export async function approveDraft({
  draftId,
  userId,
  editedText,
  businessId
}: {
  draftId: number;
  userId: number;
  editedText?: string | null;
  businessId?: number;
}): Promise<DraftMutationResult> {
  await assertDraftMutationAccess(draftId, businessId);

  const draft = await db.query.replyDrafts.findFirst({
    where: eq(replyDrafts.id, draftId)
  });

  if (!draft) {
    throw new Error('Draft not found');
  }

  const normalizedEditedText = editedText?.trim() ? editedText.trim() : null;
  const nextDraftText = normalizedEditedText ?? draft.draftText;
  const nextStatus = normalizedEditedText ? 'edited' : 'approved';
  const isAlreadyApproved =
    draft.draftText === nextDraftText &&
    draft.draftStatus === nextStatus &&
    draft.approvedByUserId === userId &&
    Boolean(draft.approvedAt);

  if (isAlreadyApproved) {
    const currentReview = await db.query.reviews.findFirst({
      where: eq(reviews.id, draft.reviewId)
    });
    if (
      currentReview &&
      (currentReview.workflowStatus !== 'approved' || currentReview.needsAttention !== false)
    ) {
      await db
        .update(reviews)
        .set({
          workflowStatus: 'approved',
          needsAttention: false,
          updatedAt: new Date()
        })
        .where(eq(reviews.id, draft.reviewId));
    }

    return {
      draft,
      wasNoop: true
    };
  }

  const [updatedDraft] = await db
    .update(replyDrafts)
    .set({
      draftText: nextDraftText,
      draftStatus: nextStatus,
      approvedByUserId: userId,
      approvedAt: new Date(),
      updatedAt: new Date()
    })
    .where(eq(replyDrafts.id, draftId))
    .returning();

  await db
    .update(reviews)
    .set({
      workflowStatus: 'approved',
      needsAttention: false,
      updatedAt: new Date()
    })
    .where(eq(reviews.id, draft.reviewId));

  return {
    draft: updatedDraft,
    wasNoop: false
  };
}

export async function rejectDraft({
  draftId,
  reason,
  businessId
}: {
  draftId: number;
  reason?: string | null;
  businessId?: number;
}): Promise<DraftMutationResult> {
  await assertDraftMutationAccess(draftId, businessId);

  const draft = await db.query.replyDrafts.findFirst({
    where: eq(replyDrafts.id, draftId)
  });

  if (!draft) {
    throw new Error('Draft not found');
  }

  const nextReason = reason ?? null;
  const isAlreadyRejected =
    draft.draftStatus === 'rejected' && draft.rejectedReason === nextReason;
  if (isAlreadyRejected) {
    const currentReview = await db.query.reviews.findFirst({
      where: eq(reviews.id, draft.reviewId)
    });
    if (
      currentReview &&
      (currentReview.workflowStatus !== 'rejected' || currentReview.needsAttention !== true)
    ) {
      await db
        .update(reviews)
        .set({
          workflowStatus: 'rejected',
          needsAttention: true,
          updatedAt: new Date()
        })
        .where(eq(reviews.id, draft.reviewId));
    }

    return {
      draft,
      wasNoop: true
    };
  }

  const [updatedDraft] = await db
    .update(replyDrafts)
    .set({
      draftStatus: 'rejected',
      rejectedReason: nextReason,
      updatedAt: new Date()
    })
    .where(eq(replyDrafts.id, draftId))
    .returning();

  await db
    .update(reviews)
    .set({
      workflowStatus: 'rejected',
      needsAttention: true,
      updatedAt: new Date()
    })
    .where(eq(reviews.id, draft.reviewId));

  return {
    draft: updatedDraft,
    wasNoop: false
  };
}

export async function markReviewPosted({
  reviewId,
  draftId,
  postedText,
  businessId
}: {
  reviewId: number;
  draftId?: number | null;
  postedText?: string | null;
  businessId?: number;
}): Promise<ReviewMutationResult> {
  await assertReviewMutationAccess(reviewId, businessId);

  const normalizedPostedText = postedText?.trim() || null;
  let draftWasNoop = true;

  if (draftId) {
    await assertDraftMutationAccess(draftId, businessId);
    const draft = await db.query.replyDrafts.findFirst({
      where: eq(replyDrafts.id, draftId)
    });
    if (!draft) {
      throw new Error('Draft not found');
    }
    if (draft.reviewId !== reviewId) {
      throw new ReviewMutationAccessError('Draft does not belong to this review.');
    }

    const isDraftAlreadyPosted =
      draft.draftStatus === 'posted_manual' &&
      draft.postedText === normalizedPostedText &&
      Boolean(draft.postedAt);

    if (!isDraftAlreadyPosted) {
      draftWasNoop = false;
      await db
        .update(replyDrafts)
        .set({
          draftStatus: 'posted_manual',
          postedAt: new Date(),
          postedText: normalizedPostedText,
          updatedAt: new Date()
        })
        .where(eq(replyDrafts.id, draftId));
    }
  }

  const review = await db.query.reviews.findFirst({
    where: eq(reviews.id, reviewId)
  });
  if (!review) {
    throw new Error('Review not found');
  }

  const isReviewAlreadyPosted =
    review.workflowStatus === 'posted_manual' &&
    review.needsAttention === false &&
    review.hasOwnerReply === true &&
    review.ownerReplyText === normalizedPostedText &&
    Boolean(review.ownerReplyUpdatedAt);

  if (isReviewAlreadyPosted) {
    return {
      review,
      wasNoop: draftWasNoop
    };
  }

  const [updatedReview] = await db
    .update(reviews)
    .set({
      workflowStatus: 'posted_manual',
      needsAttention: false,
      hasOwnerReply: true,
      ownerReplyText: normalizedPostedText,
      ownerReplyUpdatedAt: new Date(),
      updatedAt: new Date()
    })
    .where(eq(reviews.id, reviewId))
    .returning();

  return {
    review: updatedReview,
    wasNoop: false
  };
}

export async function acknowledgeNoReply({
  businessId,
  reviewId
}: {
  businessId: number;
  reviewId: number;
}) {
  const review = await getBusinessScopedReview(businessId, reviewId);
  if (!review) {
    throw new Error('Review not found');
  }

  const analysis = await db.query.reviewAnalysis.findFirst({
    where: and(eq(reviewAnalysis.reviewId, reviewId), eq(reviewAnalysis.isActive, true))
  });

  if (!analysis || analysis.actionRecommendation !== 'skip_reply') {
    throw new Error('Review is not eligible for no-reply acknowledgement');
  }

  const [updatedReview] = await db
    .update(reviews)
    .set({
      workflowStatus: 'closed_no_reply',
      needsAttention: false,
      updatedAt: new Date()
    })
    .where(eq(reviews.id, reviewId))
    .returning();

  return updatedReview;
}

export async function escalateReview({
  businessId,
  reviewId
}: {
  businessId: number;
  reviewId: number;
}): Promise<ReviewMutationResult> {
  const review = await getBusinessScopedReview(businessId, reviewId);
  if (!review) {
    throw new Error('Review not found');
  }

  const business = await db.query.businesses.findFirst({
    where: eq(businesses.id, businessId)
  });
  if (!business) {
    throw new Error('Business not found');
  }

  const ownerContact = await getBusinessOwnerContact(business.teamId);
  if (!ownerContact) {
    throw new Error('Business owner not found');
  }

  const nextWorkflowStatus =
    review.workflowStatus === 'posted_manual' || review.workflowStatus === 'closed_no_reply'
      ? review.workflowStatus
      : 'needs_attention';

  const isAlreadyEscalated =
    review.workflowStatus === nextWorkflowStatus &&
    review.needsAttention === true &&
    review.assignedUserId === ownerContact.id;

  if (isAlreadyEscalated) {
    return {
      review,
      wasNoop: true
    };
  }

  const [updatedReview] = await db
    .update(reviews)
    .set({
      workflowStatus: nextWorkflowStatus,
      needsAttention: true,
      assignedUserId: ownerContact.id,
      escalatedAt: new Date(),
      updatedAt: new Date()
    })
    .where(eq(reviews.id, reviewId))
    .returning();

  return {
    review: updatedReview,
    wasNoop: false
  };
}

export async function getReviewAnalytics(businessId: number) {
  const businessLocations = await db
    .select({ id: locations.id })
    .from(locations)
    .where(eq(locations.businessId, businessId));

  const locationIds = businessLocations.map((location) => location.id);
  if (locationIds.length === 0) {
    return {
      importedReviews: 0,
      generatedDrafts: 0,
      postedReviews: 0
    };
  }

  const [counts] = await db
    .select({
      importedReviews: sql<number>`count(*)`,
      postedReviews: sql<number>`count(*) filter (where ${reviews.workflowStatus} = 'posted_manual')`
    })
    .from(reviews)
    .where(inArray(reviews.locationId, locationIds));

  const [draftCounts] = await db
    .select({
      generatedDrafts: sql<number>`count(*)`
    })
    .from(replyDrafts)
    .leftJoin(reviews, eq(replyDrafts.reviewId, reviews.id))
    .where(inArray(reviews.locationId, locationIds));

  return {
    importedReviews: Number(counts?.importedReviews ?? 0),
    generatedDrafts: Number(draftCounts?.generatedDrafts ?? 0),
    postedReviews: Number(counts?.postedReviews ?? 0)
  };
}
