import assert from 'node:assert/strict';
import test from 'node:test';
import {
  DraftGenerationConflictError,
  assertDraftGenerationAllowed,
  shouldAutoGenerateDraft
} from '../../lib/services/reviews/draft-generation-policy.ts';

test('auto-generates only for low-risk 4-5 star reviews with high confidence', () => {
  assert.equal(
    shouldAutoGenerateDraft({
      draftGenerationMode: 'hybrid_risk_gated',
      starRating: 5,
      riskLevel: 'low',
      requiresManualReview: false,
      confidence: 80,
      actionRecommendation: 'publish_safe_reply'
    }),
    true
  );
});

test('does not auto-generate for 3-star reviews', () => {
  assert.equal(
    shouldAutoGenerateDraft({
      draftGenerationMode: 'hybrid_risk_gated',
      starRating: 3,
      riskLevel: 'low',
      requiresManualReview: false,
      confidence: 95,
      actionRecommendation: 'publish_safe_reply'
    }),
    false
  );
});

test('does not auto-generate for risky or manual-review-required reviews', () => {
  assert.equal(
    shouldAutoGenerateDraft({
      draftGenerationMode: 'hybrid_risk_gated',
      starRating: 4,
      riskLevel: 'high',
      requiresManualReview: true,
      confidence: 90,
      actionRecommendation: 'publish_safe_reply'
    }),
    false
  );
});

test('manual-only mode never auto-generates', () => {
  assert.equal(
    shouldAutoGenerateDraft({
      draftGenerationMode: 'manual_only',
      starRating: 5,
      riskLevel: 'low',
      requiresManualReview: false,
      confidence: 99,
      actionRecommendation: 'publish_safe_reply'
    }),
    false
  );
});

test('skip-reply recommendations block draft generation', () => {
  assert.throws(
    () => assertDraftGenerationAllowed('skip_reply'),
    (error: unknown) =>
      error instanceof DraftGenerationConflictError &&
      error.code === 'skip_reply_locked'
  );
});
