export const DRAFT_GENERATION_MODES = ['hybrid_risk_gated', 'manual_only'] as const;

export type DraftGenerationMode = (typeof DRAFT_GENERATION_MODES)[number];

export type DraftGenerationEligibilityInput = {
  draftGenerationMode?: string | null;
  starRating: number;
  riskLevel: string;
  requiresManualReview: boolean;
  confidence: number;
  actionRecommendation: string;
};

export type DraftGenerationConflictCode = 'skip_reply_locked';
export type DraftGenerationConflictResponse = {
  error: {
    code: DraftGenerationConflictCode;
    message: string;
  };
};

export class DraftGenerationConflictError extends Error {
  readonly code: DraftGenerationConflictCode;
  readonly status: number;

  constructor(code: DraftGenerationConflictCode, message: string) {
    super(message);
    this.name = 'DraftGenerationConflictError';
    this.code = code;
    this.status = 409;
  }
}

export function isDraftGenerationConflictError(
  error: unknown
): error is DraftGenerationConflictError {
  return error instanceof DraftGenerationConflictError;
}

export function resolveDraftGenerationMode(
  value?: string | null
): DraftGenerationMode {
  return value === 'manual_only' ? 'manual_only' : 'hybrid_risk_gated';
}

export function shouldAutoGenerateDraft(
  input: DraftGenerationEligibilityInput
) {
  const mode = resolveDraftGenerationMode(input.draftGenerationMode);
  if (mode === 'manual_only') {
    return false;
  }

  if (input.actionRecommendation !== 'publish_safe_reply') {
    return false;
  }

  if (input.starRating < 4 || input.starRating > 5) {
    return false;
  }

  if (input.riskLevel !== 'low') {
    return false;
  }

  if (input.requiresManualReview) {
    return false;
  }

  if (input.confidence < 70) {
    return false;
  }

  return true;
}

export function assertDraftGenerationAllowed(actionRecommendation: string) {
  if (actionRecommendation === 'skip_reply') {
    throw new DraftGenerationConflictError(
      'skip_reply_locked',
      'Draft generation is blocked because this review is marked as no-reply.'
    );
  }
}
